feat: :sparkles: improve home page responsive
UXCorpRangel/ana-cards-web pull request #20
Opened 2024-09-10 03:54 UTC by colmedev

### Improve home page responsive
Solving the #19 issue about responsive
https://github.com/user-attachments/assets/c3c12262-8172-4e71-a6a0-10cf098694fe

2024-09-14 03:12 UTC, colmedev commented
@felixicaza revisaaaaaa 🥺

2024-09-18 01:43 UTC, felixicaza requested changes
Por favor aplica los cambios para poder hacer el merge. ❤️

2024-09-18 01:43 UTC, felixicaza commented on src/components/CardSample.astro
> +    @media (width >= 768px) {
Mueve la media query después de la regla `@starting-style` para mantener las media queries anidadas al final de los estilos de los elementos.

2024-09-18 01:43 UTC, felixicaza commented on src/components/Footer/Footer.astro
> +        @media (width <= 640px) {
Utiliza el valor `767.98px` en su lugar para que se aplique antes del tamaño estándar para tablets.

2024-09-18 01:43 UTC, felixicaza commented on src/components/ScrollToTop.astro
> +    @media (width <= 640px) {
Utiliza el valor 767.98px en su lugar para que se aplique antes del tamaño estándar para tablets.

2024-09-18 01:43 UTC, felixicaza commented on src/components/Footer/Footer.astro
> +          margin-inline: 1rem;
Mueve la propiedad `margin-inline` debajo de `justify-content`, para mantener las propiedades que tienen que ver con flex agrupadas. 😄

2024-09-18 01:43 UTC, felixicaza commented on src/components/ScrollToTop.astro
> +      display: none;
Añade además la propiedad `content-visibility: hidden`. [Referencia](https://web.dev/articles/content-visibility).

2024-09-18 01:43 UTC, felixicaza commented on src/sections/home/Information.astro
> +        @media (width <= 768px) {
Utiliza el valor 767.98px en su lugar para que se aplique antes del tamaño estándar para tablets. Además para evitar que entre en conflicto con la siguiente media query.

2024-09-18 01:43 UTC, felixicaza commented on src/sections/home/Hero.astro
> +    @media (width >= 768px) {
Mueve la media query a la línea 42, dejando una línea en blanco entre la media query y lo demás tanto arriba y abajo.

2024-09-18 02:38 UTC, colmedev commented on src/sections/home/Hero.astro
> +    @media (width >= 768px) {
pero en esa linea hay codigo, no seria mejor colocarlo despues de todo eso?

![image](https://github.com/user-attachments/assets/5a74213f-daa0-4dd7-a73c-23741cf440f6)

2024-09-18 02:46 UTC, colmedev commented on src/sections/home/Hero.astro
> +    @media (width >= 768px) {
ya vi en donde XD

2024-09-19 01:47 UTC, merged